-- 'Core Java' training course data
INSERT INTO TRAINING_COURSE (TRAINING_COURSE_ID, NAME) VALUES (1, 'Core Java');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (1, 'Introduction to Java');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (1, 'Fundamental Programming Structures in Java');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (1, 'Objects & Classes');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (1, 'Inheritance');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (1, 'Interfaces and Inner Classes');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (1, 'Deploying Applications');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (1, 'Exceptions, Logging, assertions and Debugging');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (1, 'Generic Programming');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (1, 'Collections');

-- 'Enterprise Java' training course data
INSERT INTO TRAINING_COURSE (TRAINING_COURSE_ID, NAME) VALUES (2, 'Enterprise Java');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (2, 'Introducing Enterprise Architecture');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (2, 'Introducing Fundamental Architectural Concepts');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (2, 'Developing a Security Architecture');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (2, 'Understanding Non-Functional Requirements');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (2, 'Defining Common Problems and Solutions: Risk Factors and System Flexibility');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (2, 'Java EE 6 Overview');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (2, 'Developing an Architecture for the Client Tier');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (2, 'Developing an Architecture for the Web Tier');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (2, 'Developing an Architecture for the Business Tier');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (2, 'Developing an Architecture for the Integration and Resource Tiers');
INSERT INTO TRAINING_COURSE_SECTION (TRAINING_COURSE_ID, NAME) VALUES (2, 'Evaluating the Software Architecture');